import React from "react"
export default function Head(){
    return(
        <React.Fragment>
<title>Pure Pressure</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.svg" />  
        </React.Fragment>
        )
    
    
}